#!/usr/bin/env bash

# ~/.macos — https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
announce 'General UI/UX'
###############################################################################

# Set computer name (as done via System Preferences → Sharing)
#sudo scutil --set ComputerName "0x6D746873"
#sudo scutil --set HostName "0x6D746873"
#sudo scutil --set LocalHostName "0x6D746873"
#sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "0x6D746873"

inform_muted 'Set standby delay to 24 hours (default is 1 hour)'
sudo pmset -a standbydelay 86400

inform_muted 'Disable the sound effects on boot'
sudo nvram SystemAudioVolume=" "

inform_muted 'Disable transparency in the menu bar and elsewhere on Yosemite'
defaults write com.apple.universalaccess reduceTransparency -bool true

# Set highlight color to green
# defaults write NSGlobalDomain AppleHighlightColor -string "0.764700 0.976500 0.568600"

inform_muted 'Set sidebar icon size to medium'
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

inform_muted 'Always show scrollbars'
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

inform_muted 'Disable the over-the-top focus ring animation'
defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Disable smooth scrolling
# (Uncomment if you’re on an older Mac that messes up the animation)
#defaults write NSGlobalDomain NSScrollAnimationEnabled -bool false

inform_muted 'Increase window resize speed for Cocoa applications'
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

inform_muted 'Expand save panel by default'
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

inform_muted 'Expand print panel by default'
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

inform_muted 'Save to disk (not to iCloud) by default'
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

inform_muted 'Automatically quit printer app once the print jobs complete'
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

inform_muted 'Disable the “Are you sure you want to open this application?” dialog'
defaults write com.apple.LaunchServices LSQuarantine -bool false

inform_muted 'Remove duplicates in the “Open With” menu'
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

inform_muted 'Display ASCII control characters using caret notation in standard text views'
# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

inform_muted 'Disable Resume system-wide'
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

inform_muted 'Disable automatic termination of inactive apps'
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# inform_muted 'Disable the crash reporter'
#defaults write com.apple.CrashReporter DialogType -string "none"

inform_muted 'Set Help Viewer windows to non-floating mode'
defaults write com.apple.helpviewer DevMode -bool true

# Fix for the ancient UTF-8 bug in QuickLook (https://mths.be/bbo)
# Commented out, as this is known to cause problems in various Adobe apps :(
# See https://github.com/mathiasbynens/dotfiles/issues/237
#echo "0x08000100:0" > ~/.CFUserTextEncoding

inform_muted 'Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window'
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

inform_muted 'Restart automatically if the computer freezes'
sudo systemsetup -setrestartfreeze on

inform_muted 'Never go into computer sleep mode'
sudo systemsetup -setcomputersleep Off > /dev/null

inform_muted 'Disable Notification Center and remove the menu bar icon'
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

inform_muted 'Disable automatic capitalization as it’s annoying when typing code'
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

inform_muted 'Disable smart dashes as they’re annoying when typing code'
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

inform_muted 'Disable automatic period substitution as it’s annoying when typing code'
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

inform_muted 'Disable smart quotes as they’re annoying when typing code'
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

inform_muted 'Disable auto-correct'
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Set a custom wallpaper image. `DefaultDesktop.jpg` is already a symlink, and
# all wallpapers are in `/Library/Desktop Pictures/`. The default is `Wave.jpg`.
#rm -rf ~/Library/Application Support/Dock/desktoppicture.db
#sudo rm -rf /System/Library/CoreServices/DefaultDesktop.jpg
#sudo ln -s /path/to/your/image /System/Library/CoreServices/DefaultDesktop.jpg

###############################################################################
announce 'SSD-specific tweaks'
###############################################################################

inform_muted 'Disable hibernation (speeds up entering sleep mode)'
sudo pmset -a hibernatemode 0

# inform_muted 'Remove the sleep image file to save disk space'
# sudo rm /private/var/vm/sleepimage

# inform_muted 'Create a zero-byte file instead…'
# sudo touch /private/var/vm/sleepimage

# inform_muted '…and make sure it can’t be rewritten'
# sudo chflags uchg /private/var/vm/sleepimage

###############################################################################
announce 'Trackpad, mouse, keyboard, Bluetooth accessories, and input'
###############################################################################

inform_muted 'Trackpad: enable tap to click for this user and for the login screen'
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

inform_muted 'Trackpad: map bottom right corner to right-click'
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# inform_muted 'Disable “natural” (Lion-style) scrolling'
# defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

inform_muted 'Increase sound quality for Bluetooth headphones/headsets'
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

inform_muted 'Enable full keyboard access for all controls'
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

inform_muted 'Use scroll gesture with the Ctrl (^) modifier key to zoom'
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

inform_muted 'Follow the keyboard focus while zoomed in'
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

inform_muted 'Disable press-and-hold for keys in favor of key repeat'
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

inform_muted 'Set a blazingly fast keyboard repeat rate'
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

inform_muted 'Set language and text formats to European'
# Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
# `Inches`, `en_GB` with `en_US`, and `true` with `false`.
defaults write NSGlobalDomain AppleLanguages -array "en" "nl"
defaults write NSGlobalDomain AppleLocale -string "en_GB@currency=EUR"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

inform_muted 'Show language menu in the top right corner of the boot screen'
sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true

# inform_muted 'Set the timezone; see `sudo systemsetup -listtimezones` for other values'
# sudo systemsetup -settimezone "Europe/Brussels" > /dev/null

# inform_muted 'Stop iTunes from responding to the keyboard media keys'
#launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

###############################################################################
announce 'Screen'
###############################################################################

inform_muted 'Require password immediately after sleep or screen saver begins'
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

inform_muted 'Save screenshots to the desktop'
defaults write com.apple.screencapture location -string "${HOME}/Desktop"

inform_muted 'Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)'
defaults write com.apple.screencapture type -string "png"

inform_muted 'Disable shadow in screenshots'
defaults write com.apple.screencapture disable-shadow -bool true

inform_muted 'Enable subpixel font rendering on non-Apple LCDs'
# Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

inform_muted 'Enable HiDPI display modes (requires restart)'
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

###############################################################################
announce 'Finder'
###############################################################################

inform_muted 'Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons'
defaults write com.apple.finder QuitMenuItem -bool true

inform_muted 'Finder: disable window animations and Get Info animations'
defaults write com.apple.finder DisableAllAnimations -bool true

inform_muted 'Set Desktop as the default location for new Finder windows'
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

inform_muted 'Show icons for hard drives, servers, and removable media on the desktop'
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

inform_muted 'Finder: show hidden files by default'
defaults write com.apple.finder AppleShowAllFiles -bool true

inform_muted 'Finder: show all filename extensions'
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

inform_muted 'Finder: show status bar'
defaults write com.apple.finder ShowStatusBar -bool true

inform_muted 'Finder: show path bar'
defaults write com.apple.finder ShowPathbar -bool true

inform_muted 'Display full POSIX path as Finder window title'
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

inform_muted 'Keep folders on top when sorting by name'
defaults write com.apple.finder _FXSortFoldersFirst -bool true

inform_muted 'When performing a search, search the current folder by default'
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

inform_muted 'Disable the warning when changing a file extension'
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

inform_muted 'Enable spring loading for directories'
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

inform_muted 'Remove the spring loading delay for directories'
defaults write NSGlobalDomain com.apple.springing.delay -float 0

inform_muted 'Avoid creating .DS_Store files on network or USB volumes'
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

inform_muted 'Disable disk image verification'
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

inform_muted 'Automatically open a new Finder window when a volume is mounted'
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

inform_muted 'Show item info near icons on the desktop and in other icon views'
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

inform_muted 'Show item info to the right of the icons on the desktop'
/usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

inform_muted 'Enable snap-to-grid for icons on the desktop and in other icon views'
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

inform_muted 'Increase grid spacing for icons on the desktop and in other icon views'
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 100" ~/Library/Preferences/com.apple.finder.plist

inform_muted 'Increase the size of icons on the desktop and in other icon views'
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 80" ~/Library/Preferences/com.apple.finder.plist

inform_muted 'Use list view in all Finder windows by default'
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

inform_muted 'Disable the warning before emptying the Trash'
defaults write com.apple.finder WarnOnEmptyTrash -bool false

inform_muted 'Enable AirDrop over Ethernet and on unsupported Macs running Lion'
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

inform_muted 'Show the ~/Library folder'
chflags nohidden ~/Library

inform_muted 'Show the /Volumes folder'
sudo chflags nohidden /Volumes

inform_muted 'Remove Dropbox’s green checkmark icons in Finder'
file=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns
[ -e "${file}" ] && mv -f "${file}" "${file}.bak"

inform_muted 'Expand the File Info panes'
# “General”, “Open with”, and “Sharing & Permissions”
defaults write com.apple.finder FXInfoPanesExpanded -dict \
  General -bool true \
  OpenWith -bool true \
  Privileges -bool true

###############################################################################
announce 'Dock, Dashboard, and hot corners'
###############################################################################

inform_muted 'Enable highlight hover effect for the grid view of a stack (Dock)'
defaults write com.apple.dock mouse-over-hilite-stack -bool true

inform_muted 'Set the icon size of Dock items to 36 pixels'
defaults write com.apple.dock tilesize -int 36

inform_muted 'Change minimize/maximize window effect'
defaults write com.apple.dock mineffect -string "scale"

inform_muted 'Minimize windows into their application’s icon'
defaults write com.apple.dock minimize-to-application -bool true

inform_muted 'Enable spring loading for all Dock items'
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

inform_muted 'Show indicator lights for open applications in the Dock'
defaults write com.apple.dock show-process-indicators -bool true

inform_muted 'Wipe all (default) app icons from the Dock'
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

inform_muted 'Show only open applications in the Dock'
defaults write com.apple.dock static-only -bool true

inform_muted 'Don’t animate opening applications from the Dock'
defaults write com.apple.dock launchanim -bool false

inform_muted 'Speed up Mission Control animations'
defaults write com.apple.dock expose-animation-duration -float 0.1

inform_muted 'Don’t group windows by application in Mission Control'
# (i.e. use the old Exposé behavior instead)
defaults write com.apple.dock expose-group-by-app -bool false

inform_muted 'Disable Dashboard'
defaults write com.apple.dashboard mcx-disabled -bool true

inform_muted 'Don’t show Dashboard as a Space'
defaults write com.apple.dock dashboard-in-overlay -bool true

inform_muted 'Don’t automatically rearrange Spaces based on most recent use'
defaults write com.apple.dock mru-spaces -bool false

inform_muted 'Remove the auto-hiding Dock delay'
defaults write com.apple.dock autohide-delay -float 0
inform_muted 'Remove the animation when hiding/showing the Dock'
defaults write com.apple.dock autohide-time-modifier -float 0

inform_muted 'Automatically hide and show the Dock'
defaults write com.apple.dock autohide -bool true

inform_muted 'Make Dock icons of hidden applications translucent'
defaults write com.apple.dock showhidden -bool true

inform_muted 'Don’t show recent applications in Dock'
defaults write com.apple.dock show-recents -bool false

inform_muted 'Disable the Launchpad gesture (pinch with thumb and three fingers)'
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

inform_muted 'Reset Launchpad, but keep the desktop wallpaper intact'
find "${HOME}/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete

inform_muted 'Add iOS & Watch Simulator to Launchpad'
sudo ln -sf "/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app" "/Applications/Simulator.app"
sudo ln -sf "/Applications/Xcode.app/Contents/Developer/Applications/Simulator (Watch).app" "/Applications/Simulator (Watch).app"

# Add a spacer to the left side of the Dock (where the applications are)
#defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
# Add a spacer to the right side of the Dock (where the Trash is)
#defaults write com.apple.dock persistent-others -array-add '{tile-data={}; tile-type="spacer-tile";}'

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
inform_muted 'Hot corners: Top left screen corner → Mission Control'
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0
inform_muted 'Hot corners: Top right screen corner → Desktop'
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0
inform_muted 'Hot corners: Bottom left screen corner → Start screen saver'
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0

###############################################################################
announce 'Safari & WebKit'
###############################################################################

inform_muted 'Privacy: don’t send search queries to Apple'
defaults write com.apple.Safari UniversalSearchEnabled -bool false
defaults write com.apple.Safari SuppressSearchSuggestions -bool true

inform_muted 'Press Tab to highlight each item on a web page'
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

inform_muted 'Show the full URL in the address bar (note: this still hides the scheme)'
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

inform_muted 'Set Safari’s home page to `about:blank` for faster loading'
defaults write com.apple.Safari HomePage -string "about:blank"

inform_muted 'Prevent Safari from opening ‘safe’ files automatically after downloading'
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

inform_muted 'Allow hitting the Backspace key to go to the previous page in history'
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

inform_muted 'Hide Safari’s bookmarks bar by default'
defaults write com.apple.Safari ShowFavoritesBar -bool false

inform_muted 'Hide Safari’s sidebar in Top Sites'
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

inform_muted 'Disable Safari’s thumbnail cache for History and Top Sites'
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

inform_muted 'Enable Safari’s debug menu'
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

inform_muted 'Make Safari’s search banners default to Contains instead of Starts With'
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

inform_muted 'Remove useless icons from Safari’s bookmarks bar'
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

inform_muted 'Enable the Develop menu and the Web Inspector in Safari'
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

inform_muted 'Add a context menu item for showing the Web Inspector in web views'
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

inform_muted 'Enable continuous spellchecking'
defaults write com.apple.Safari WebContinuousSpellCheckingEnabled -bool true
inform_muted 'Disable auto-correct'
defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false

inform_muted 'Disable AutoFill'
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

inform_muted 'Warn about fraudulent websites'
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

inform_muted 'Disable plug-ins'
defaults write com.apple.Safari WebKitPluginsEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false

inform_muted 'Disable Java'
defaults write com.apple.Safari WebKitJavaEnabled -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false

inform_muted 'Block pop-up windows'
defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false

# inform_muted 'Disable auto-playing video'
#defaults write com.apple.Safari WebKitMediaPlaybackAllowsInline -bool false
#defaults write com.apple.SafariTechnologyPreview WebKitMediaPlaybackAllowsInline -bool false
#defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false
#defaults write com.apple.SafariTechnologyPreview com.apple.Safari.ContentPageGroupIdentifier.WebKit2AllowsInlineMediaPlayback -bool false

inform_muted 'Enable “Do Not Track”'
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

inform_muted 'Update extensions automatically'
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

###############################################################################
announce 'Mail'
###############################################################################

inform_muted 'Disable send and reply animations in Mail.app'
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true

inform_muted 'Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>`'
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

inform_muted 'Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app'
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" "@\U21a9"

inform_muted 'Display emails in threaded mode, sorted by date (oldest at the top)'
defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

inform_muted 'Disable inline attachments (just show the icons)'
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

inform_muted 'Disable automatic spell checking'
defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"

###############################################################################
announce 'Spotlight'
###############################################################################

# Hide Spotlight tray-icon (and subsequent helper)
#sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
inform_muted 'Disable Spotlight indexing for any volume that gets mounted and has not yet been indexed before.'
# Use `sudo mdutil -i off "/Volumes/foo"` to stop indexing any volume.
sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

# inform_muted 'Change indexing order and disable some search results'
# Yosemite-specific search results (remove them if you are using macOS 10.9 or older):
#   MENU_DEFINITION
#   MENU_CONVERSION
#   MENU_EXPRESSION
#   MENU_SPOTLIGHT_SUGGESTIONS (send search queries to Apple)
#   MENU_WEBSEARCH             (send search queries to Apple)
#   MENU_OTHER
# defaults write com.apple.spotlight orderedItems -array \
#   '{"enabled" = 1;"name" = "APPLICATIONS";}' \
#   '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
#   '{"enabled" = 1;"name" = "DIRECTORIES";}' \
#   '{"enabled" = 1;"name" = "PDF";}' \
#   '{"enabled" = 1;"name" = "FONTS";}' \
#   '{"enabled" = 0;"name" = "DOCUMENTS";}' \
#   '{"enabled" = 0;"name" = "MESSAGES";}' \
#   '{"enabled" = 0;"name" = "CONTACT";}' \
#   '{"enabled" = 0;"name" = "EVENT_TODO";}' \
#   '{"enabled" = 0;"name" = "IMAGES";}' \
#   '{"enabled" = 0;"name" = "BOOKMARKS";}' \
#   '{"enabled" = 0;"name" = "MUSIC";}' \
#   '{"enabled" = 0;"name" = "MOVIES";}' \
#   '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
#   '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
#   '{"enabled" = 0;"name" = "SOURCE";}' \
#   '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
#   '{"enabled" = 0;"name" = "MENU_OTHER";}' \
#   '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
#   '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
#   '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
#   '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

# inform_muted 'Load new settings before rebuilding the index'
# killall mds > /dev/null 2>&1

# inform_muted 'Make sure indexing is enabled for the main volume'
# sudo mdutil -i on / > /dev/null

# inform_muted 'Rebuild the index from scratch'
# sudo mdutil -E / > /dev/null

###############################################################################
announce 'Terminal & iTerm 2'
###############################################################################

inform_muted 'Only use UTF-8 in Terminal.app'
defaults write com.apple.terminal StringEncodings -array 4

# inform_muted 'Use a modified version of the Solarized Dark theme by default in Terminal.app'
# osascript <<EOD

# tell application "Terminal"

#   local allOpenedWindows
#   local initialOpenedWindows
#   local windowID
#   set themeName to "Solarized Dark xterm-256color"

#   (* Store the IDs of all the open terminal windows. *)
#   set initialOpenedWindows to id of every window

#   (* Open the custom theme so that it gets added to the list
#      of available terminal themes (note: this will open two
#      additional terminal windows). *)
#   do shell script "open '$HOME/init/" & themeName & ".terminal'"

#   (* Wait a little bit to ensure that the custom theme is added. *)
#   delay 1

#   (* Set the custom theme as the default terminal theme. *)
#   set default settings to settings set themeName

#   (* Get the IDs of all the currently opened terminal windows. *)
#   set allOpenedWindows to id of every window

#   repeat with windowID in allOpenedWindows

#     (* Close the additional windows that were opened in order
#        to add the custom theme to the list of terminal themes. *)
#     if initialOpenedWindows does not contain windowID then
#       close (every window whose id is windowID)

#     (* Change the theme for the initial opened terminal windows
#        to remove the need to close them in order for the custom
#        theme to be applied. *)
#     else
#       set current settings of tabs of (every window whose id is windowID) to settings set themeName
#     end if

#   end repeat

# end tell

# EOD

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
#defaults write com.apple.terminal FocusFollowsMouse -bool true
#defaults write org.x.X11 wm_ffm -bool true

inform_muted 'Enable Secure Keyboard Entry in Terminal.app'
# See: https://security.stackexchange.com/a/47786/8918
defaults write com.apple.terminal SecureKeyboardEntry -bool true

inform_muted 'Disable the annoying line marks'
defaults write com.apple.Terminal ShowLineMarks -int 0

# Install the Solarized Dark theme for iTerm
# open "${HOME}/init/Solarized Dark.itermcolors"

inform_muted 'Don’t display the annoying prompt when quitting iTerm'
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

###############################################################################
announce 'Time Machine'
###############################################################################

inform_muted 'Prevent Time Machine from prompting to use new hard drives as backup volume'
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# inform_muted 'Disable local Time Machine backups'
# hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
announce 'Activity Monitor'
###############################################################################

inform_muted 'Show the main window when launching Activity Monitor'
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

inform_muted 'Visualize CPU usage in the Activity Monitor Dock icon'
defaults write com.apple.ActivityMonitor IconType -int 5

inform_muted 'Show all processes in Activity Monitor'
defaults write com.apple.ActivityMonitor ShowCategory -int 0

inform_muted 'Sort Activity Monitor results by CPU usage'
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

###############################################################################
announce 'Address Book, Dashboard, iCal, TextEdit, and Disk Utility'
###############################################################################

inform_muted 'Enable the debug menu in Address Book'
defaults write com.apple.addressbook ABShowDebugMenu -bool true

inform_muted 'Enable Dashboard dev mode (allows keeping widgets on the desktop)'
defaults write com.apple.dashboard devmode -bool true

inform_muted 'Enable the debug menu in iCal (pre-10.8)'
defaults write com.apple.iCal IncludeDebugMenu -bool true

inform_muted 'Use plain text mode for new TextEdit documents'
defaults write com.apple.TextEdit RichText -int 0
inform_muted 'Open and save files as UTF-8 in TextEdit'
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

inform_muted 'Enable the debug menu in Disk Utility'
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
defaults write com.apple.DiskUtility advanced-image-options -bool true

inform_muted 'Auto-play videos when opened with QuickTime Player'
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen -bool true

###############################################################################
announce 'Mac App Store'
###############################################################################

inform_muted 'Enable the WebKit Developer Tools in the Mac App Store'
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

inform_muted 'Enable Debug Menu in the Mac App Store'
defaults write com.apple.appstore ShowDebugMenu -bool true

inform_muted 'Enable the automatic update check'
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

inform_muted 'Check for software updates daily, not just once per week'
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

inform_muted 'Download newly available updates in background'
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

inform_muted 'Install System data files & security updates'
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

inform_muted 'Automatically download apps purchased on other Macs'
defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

inform_muted 'Turn on app auto-update'
defaults write com.apple.commerce AutoUpdate -bool true

inform_muted 'Allow the App Store to reboot machine on macOS updates'
defaults write com.apple.commerce AutoUpdateRestartRequired -bool true

###############################################################################
announce 'Photos'
###############################################################################

inform_muted 'Prevent Photos from opening automatically when devices are plugged in'
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

###############################################################################
announce 'Messages'
###############################################################################

# Disable automatic emoji substitution (i.e. use plain text smileys)
# defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

inform_muted 'Disable smart quotes as it’s annoying for messages that contain code'
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# Disable continuous spell checking
# defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
announce 'Google Chrome & Google Chrome Canary'
###############################################################################

inform_muted 'Disable the all too sensitive backswipe on trackpads'
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false

inform_muted 'Disable the all too sensitive backswipe on Magic Mouse'
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false

inform_muted 'Use the system-native print preview dialog'
defaults write com.google.Chrome DisablePrintPreview -bool true
defaults write com.google.Chrome.canary DisablePrintPreview -bool true

inform_muted 'Expand the print dialog by default'
defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true
defaults write com.google.Chrome.canary PMPrintingExpandedStateForPrint2 -bool true

###############################################################################
# GPGMail 2                                                                   #
###############################################################################

# Disable signing emails by default
# defaults write ~/Library/Preferences/org.gpgtools.gpgmail SignNewEmailsByDefault -bool false

###############################################################################
# Opera & Opera Developer                                                     #
###############################################################################

# Expand the print dialog by default
defaults write com.operasoftware.Opera PMPrintingExpandedStateForPrint2 -boolean true
defaults write com.operasoftware.OperaDeveloper PMPrintingExpandedStateForPrint2 -boolean true

###############################################################################
# Sublime Text                                                                #
###############################################################################

# Install Sublime Text settings
# cp -r init/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null

###############################################################################
# Spectacle.app                                                               #
###############################################################################

# Set up my preferred keyboard shortcuts
# cp -r init/spectacle.json ~/Library/Application\ Support/Spectacle/Shortcuts.json 2> /dev/null

###############################################################################
announce 'Transmission.app'
###############################################################################

inform_muted 'Use `~/Documents/Torrents` to store incomplete downloads'
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Documents/Torrents"

inform_muted 'Use `~/Downloads` to store completed downloads'
defaults write org.m0k.transmission DownloadLocationConstant -bool true

inform_muted 'Don’t prompt for confirmation before downloading'
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission MagnetOpenAsk -bool false

inform_muted 'Don’t prompt for confirmation before removing non-downloading active transfers'
defaults write org.m0k.transmission CheckRemoveDownloading -bool true

inform_muted 'Trash original torrent files'
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

inform_muted 'Hide the donate message'
defaults write org.m0k.transmission WarningDonate -bool false

inform_muted 'Hide the legal disclaimer'
defaults write org.m0k.transmission WarningLegal -bool false

inform_muted 'IP block list.'
# Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
defaults write org.m0k.transmission BlocklistNew -bool true
defaults write org.m0k.transmission BlocklistURL -string "http://john.bitsurge.net/public/biglist.p2p.gz"
defaults write org.m0k.transmission BlocklistAutoUpdate -bool true

inform_muted 'Randomize port on launch'
defaults write org.m0k.transmission RandomPort -bool true

###############################################################################
# Twitter.app                                                                 #
###############################################################################

# Disable smart quotes as it’s annoying for code tweets
# defaults write com.twitter.twitter-mac AutomaticQuoteSubstitutionEnabled -bool false

# Show the app window when clicking the menu bar icon
# defaults write com.twitter.twitter-mac MenuItemBehavior -int 1

# Enable the hidden ‘Develop’ menu
# defaults write com.twitter.twitter-mac ShowDevelopMenu -bool true

# Open links in the background
# defaults write com.twitter.twitter-mac openLinksInBackground -bool true

# Allow closing the ‘new tweet’ window by pressing `Esc`
# defaults write com.twitter.twitter-mac ESCClosesComposeWindow -bool true

# Show full names rather than Twitter handles
# defaults write com.twitter.twitter-mac ShowFullNames -bool true

# Hide the app in the background if it’s not the front-most window
# defaults write com.twitter.twitter-mac HideInBackground -bool true

###############################################################################
# Tweetbot.app                                                                #
###############################################################################

# Bypass the annoyingly slow t.co URL shortener
# defaults write com.tapbots.TweetbotMac OpenURLsDirectly -bool true

###############################################################################
# announce 'Kill affected applications'
###############################################################################

# for app in "Activity Monitor" \
#   "Address Book" \
#   "Calendar" \
#   "cfprefsd" \
#   "Contacts" \
#   "Dock" \
#   "Finder" \
#   "Google Chrome" \
#   "Mail" \
#   "Messages" \
#   "Photos" \
#   "Safari" \
#   "SystemUIServer" \
#   "Terminal" \
#   "Transmission" \
#   "iCal"; do
#   killall "${app}" &> /dev/null
# done

print_in_green "${bold}✓ Done!${normal}\n"
print_in_green "Note that some of these changes require a logout/restart to take effect."
